language: python
python:
  - "3.6"
install:
  - pip install Nose coverage codacy-coverage
script:
  - nosetests --with-coverage --cover-package=main --cover-xml
after_success:
  - python-codacy-coverage
